// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { NotificationsProvider } from "@/contexts/NotificationsContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "ALL - Professional Networking & Jobs",
//   description: "A complete professional networking and job platform focused on Tier 2 & 3 cities in India",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <NotificationsProvider>
//           {children}
//         </NotificationsProvider>
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { NotificationsProvider } from "@/contexts/NotificationsContext";
// import ClientErrorBoundary from "@/components/ClientErrorBoundary";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "ALL - Professional Networking & Jobs",
//   description: "A complete professional networking and job platform focused on Tier 2 & 3 cities in India",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ClientErrorBoundary fallbackMessage="The application encountered an unexpected error">
//           <NotificationsProvider>
//             {children}
//           </NotificationsProvider>
//         </ClientErrorBoundary>
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// import { ThemeProvider } from "@/contexts/ThemeContext";
// import { NotificationsProvider } from "@/contexts/NotificationsContext";
// import ClientErrorBoundary from "@/components/ClientErrorBoundary";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "ALL - Professional Networking & Jobs",
//   description: "A complete professional networking and job platform focused on Tier 2 & 3 cities in India",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ClientErrorBoundary fallbackMessage="The application encountered an unexpected error">
//           <ThemeProvider>
//             <NotificationsProvider>
//               {children}
//             </NotificationsProvider>
//           </ThemeProvider>
//         </ClientErrorBoundary>
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// import { NotificationsProvider } from "@/contexts/NotificationsContext";
// import ClientErrorBoundary from "@/components/ClientErrorBoundary";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "ALL - Professional Networking & Jobs",
//   description: "A complete professional networking and job platform focused on Tier 2 & 3 cities in India",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ClientErrorBoundary fallbackMessage="The application encountered an unexpected error">
//           <NotificationsProvider>
//             {children}
//           </NotificationsProvider>
//         </ClientErrorBoundary>
//       </body>
//     </html>
//   );
// }

// -------------------- working one -----------------

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// import { NotificationsProvider } from "@/contexts/NotificationsContext";
// import ClientErrorBoundary from "@/components/ClientErrorBoundary";
// import FeedbackButton from "@/components/FeedbackButton"; // Added import

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "ALL - Professional Networking & Jobs",
//   description: "A complete professional networking and job platform focused on Tier 2 & 3 cities in India",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ClientErrorBoundary fallbackMessage="The application encountered an unexpected error">
//           <NotificationsProvider>
//             {children}
//             {/* Added Feedback Button Here */}
//             <FeedbackButton />
//           </NotificationsProvider>
//         </ClientErrorBoundary>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// ✅ FIXED: Using the absolute alias pathing prevents TypeScript module errors
import "@/app/globals.css"; 
import { NotificationsProvider } from "@/contexts/NotificationsContext";
import ClientErrorBoundary from "@/components/ClientErrorBoundary";
import FeedbackButton from "@/components/FeedbackButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ALL - Professional Networking & Jobs",
  description: "A complete professional networking and job platform focused on Tier 2 & 3 cities in India",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientErrorBoundary fallbackMessage="The application encountered an unexpected error">
          <NotificationsProvider>
            {children}
            {/* Added Feedback Button Here */}
            <FeedbackButton />
          </NotificationsProvider>
        </ClientErrorBoundary>
      </body>
    </html>
  );
}